name: Test Self-Hosted Runner

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run a simple command
      run: echo "Self-hosted runner is working!"

    - name: Display system info
      run: |
        uname -a
        df -h
        free -m
